spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#openapi:
#  service:
#    api-docs: backend-service
#    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
#    title: E-learning API Document
#    version: 1.0.0
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true