server:
  port: 8080

spring:
  application:
    name: e-learning-system-api
  profiles:
    active: @spring.profiles.active@

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#logging:
#  level:
#    root: INFO
#    web: INFO